### ISSUE TITLE
About Placeholder and Track Number

### ISSUE THREAD

**Issue by 921j** [TT-ReBORN/Georgia-ReBORN#186] opened 2024-07-15 22:49 UTC
![2024-07-16_061841](https://github.com/user-attachments/assets/30914507-f894-4463-bb3b-1fa008a4943b)

As shown in the above figure, there are one requisition and one bug:
1. Could make the background of the Placeholder flow the artist or disc pictures jusk like the introduction, but keep the stylus and desktop etc?
When just listening to the single songs, this interface looks very abrupt.

2. When the song's format is AAC, the artist's name and track number will overlapping, other format not. ( use custom fonts ).

3. I want to integrate MusicTag into the right context menu of the playlist. What should I do?
In addition, I found that when changing the context menu in the preferences of Foobar2000, it does not work.

**Comment by TT-ReBORN** [comment] 2024-07-17 15:30
Hi @921j,

I'm not sure what Georgia-ReBORN version you are using, 
but I do not have any issues you described in 2 and 3 with the DEV version from here:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

I also do not really understand what you mean in your first point (1). 
There is no disc art in the Playlist panel, it is only displayed and available in the Details panel.

-TT

**Comment by 921j** [comment] 2024-07-17 17:22
Thank you!
I have tried using a "pure" Foobar2000 version with your Georgia-ReBORN, and the embedded cover is also displayed in the playlist interface, but I still hope it can be a rotating disc with cover,jusk like "Details", so that I don't have to switch between Details and playlist when listening to a lots of single songs.
There is no problem with change the context menu in the preferences, but the artist name and track number are still overlapping when playing AAC. I did not install the fonts in georgia-reborn to Win10, but used the foo_ui_hacks font loading function. Although the font error is prompted every time it is started, I don't want to install so many fonts to the Windows system. The strange thing is that there is no such problem when playing music in other formats.

![2024-07-18_003827](https://github.com/user-attachments/assets/cb35b0b1-5925-4e93-b8a0-5489556a0fca)

**Comment by TT-ReBORN** [comment] 2024-07-17 19:48
Strange, I have tested some AAC test files and it did not encounter this bug. 

From the screenshot, it seems the issue is related that metadata being not correctly parsed.
Can you zip this AAC file and post it here? I'll delete it afterwards.
Thanks!

-TT

**Comment by 921j** [comment] 2024-07-18 02:12
There is:
[中島みゆき - 地上の星.zip](https://github.com/user-attachments/files/16276659/-.zip)

Encountered a supernatural event!
After using Freemake Audio Converter to convert this AAC file to "AAC" again, Georgia-ReBORN displays normally, but I can't write tags to it, even using MusicTag.

**Comment by TT-ReBORN** [comment] 2024-07-18 09:09
I have tried to extract the song from the zip but I get a message that the file is bad, it's 0 byte when extracted. 
So it seems your source files are corrupt and that is why it can not be read properly...

**Comment by 921j** [comment] 2024-07-18 12:20
[1.zip](https://github.com/user-attachments/files/16283066/1.zip)

Strange, I can download, decompress and play this zip normally.
I repacked it with WinRAR to zip and upload for you.
It is not just that this AAC file has this problem, all AAC songs on my computer is.
In addition, I played these AAC files with MPV and Potplayer, which can determine that they are indeed a AAC format encoding file.

**Comment by TT-ReBORN** [comment] 2024-07-18 19:12
Thanks for the new zip file, now I can extract it successfully and I can confirm the bug.
I have never encountered this issue and it is indeed really strange ( doesn't even show track length )... 

At the moment I am really busy because I'm rewriting and refactoring the code of Georgia-ReBORN.
There will be lots of improvements and once I have some time I will take a look and let you know when the fix is available.

-TT

**Comment by 921j** [comment] 2024-07-19 05:47
Thanks, take good care of yourself no matter how busy you are!
We will look forward to a more gorgeous and elegant Georgia-ReBORN!

**Comment by TT-ReBORN** [comment] 2024-08-15 19:21
@921j,

check the latest RC-3 beta version now in the master here:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

The issue should be fixed.

-TT

**Closed by TT-ReBORN** 2024-08-15 19:21 UTC

**Comment by silverwings15** [comment] 2024-08-15 19:30
just read the RC3 changelog.. can't express enough of my appreciation for this super massive rewrite, no wonder why you took your time. i'm F5ing like mad waiting for the announcement to go live in DEV TESTING to start posting bugs 😁

**Comment by TT-ReBORN** [comment] 2024-08-15 19:35
Wait a minute, I need to check some things before I post it in the DEV thread :sweat_smile:
