### ISSUE TITLE
bug when clicking some where in the menu bar and/or menu elements

### ISSUE THREAD

**Issue by urielejh** [TT-ReBORN/Georgia-ReBORN#179] opened 2024-03-31 10:49 UTC
Hi,

when i click menu items (eg. options, playlist, and so on) the track forwards or backwards...

**Comment by TT-ReBORN** [comment] 2024-03-31 11:17
Hi @urielejh,

did you try the DEV version? Here is the link:
https://github.com/TT-ReBORN/Georgia-ReBORN/archive/refs/heads/master.zip

If this is not working for you, then you need to tell me step by step how to reproduce and what desktop resolution
you are using, because other users would report about this issue much sooner!

-TT

**Comment by urielejh** [comment] 2024-04-03 08:04
it still happens. 4k monitor and 4k player. i tried with autodetect and the other res. and the issue's still there. however, when selecting 4k again it seems to happen only when a menu voice is selected and one clicks over the menu bar

**Comment by TT-ReBORN** [comment] 2024-04-03 11:57
I have tried the DEV version on 4K monitor with 4K res and also tried other lower resolutions and I can not reproduce 
your issues, all seems working fine...

Seeking track playback should only happen when your mouse is in the progress bar area and when you do 
a left drag mouse click.

Are you using the original files without any additional user-components and/or shortcuts?
**As previously mentioned above, to be able to fix it, I need step by step instructions how to reproduce your issue.
Tell me exactly what you are doing, you are using 3840 x 2160 desktop resolution on a 4K monitor and then where are
you clicking???**

**Comment by urielejh** [comment] 2024-04-04 17:11
- 4k monitor@native resolution and 100% scaling
- ![image](https://github.com/TT-ReBORN/Georgia-ReBORN/assets/89837935/d7dab614-3f72-4d14-80c4-96748a974439)
- no custom theme, just reborn. i added waveform minibar
- i play a track
- i click on a menu voice (like option)
- click somewhere else in the menu bar
- the track skips forward or backward

**Comment by TT-ReBORN** [comment] 2024-04-04 18:16
Of course this would not work, your layout is broken because you added a new panel vertically.
This is not supported and because of it, the seekbar drag area is borked. Remove the waveform bar mini mod
panel or make a new fresh foobar installation with the theme.

**There already is a waveform bar implemented, if you right click on the seekbar, select waveform bar.**

Closing this as there is no issue.

-TT

**Comment by urielejh** [comment] 2024-04-04 18:58
oh, i see. thank you!

**Closed** 2024-04-04 19:47 UTC
